### ISSUE TITLE
Is this frequently updated?

### ISSUE THREAD

**Issue by James-Thorson** [INBO-BMK/INLA#1]
This looks like a neat option to automatically download INLA as a dependency of a package by including it in the Removes section of the DESCRIPTION file.  However, this would only be a good idea if `inbo/INLA` routlinely mirrors the INLA download from their website.  

How often do you mirror the INLA website, and is it automated?  Is there any checks to ensure that the download is identical from the two sources?

And thanks for re-serving INLA!

**Comment by ThierryO** [comment]
The purpose of this repo is to serve as a backup for specific versions of INLA which we use for our analysis. Currently the repository is updated manually and ad hoc. We have no plans to automate it or to do it frequently.

The procedure is simple:

1. download tar.gz from the INLA website
1. unpack it into to repo
1. commit the changes
1. push the changes to the repo
1. create a release

**Comment by ThierryO** [comment]
The update is actually not ad hoc. It gets updated when https://github.com/inbo/rstable is upgraded to the latest R version.
